#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web01
    username: root
    password: yinweisuoyi
#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 定义对象/Map集合
user:
  name: may
  age: 23
  password: 123456

# 定义数组/List/Set集合
hobby:
  - java
  - game
  - sport

# 在yml格式的配置文件中，如果配置项的值是以0 开头的，值需要使用 ' ' 引起来，因为以0开头在yml中表示8进制的数据。